import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Malomba Cleaners",
  description: "Generated by EJ_Pixels",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex min-h-screen flex-col bg-gray-100 overflow-x-hidden"
      >
        <Navbar />
        <main className="container mx-auto px-4 py-8 flex-grow">
          {children}
        </main> 
        <Footer />
      </body>
    </html>
  );
}
