import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShineySpaces",
  description: "Generated by EJ_Pixels",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className={`flex min-h-screen flex-col bg-gray-100 overflow-x-hidden ${poppins.variable}`}
      >
        <Navbar />
        <main className="container mx-auto py-8 flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
